---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/apps
  prune: true
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
